# LogWatchdog Configuration File
# =============================
# This file was automatically created by LogWatchdog.
# Modify the values below to customize your monitoring setup.

[monitoring]
monitor_mode = folder
log_file_path = C:\Users\pandi\Documents\GitHub\logwatchdog\test_clean\logs\application.log
log_files = C:\Users\pandi\Documents\GitHub\logwatchdog\test_clean\logs\app.log,C:\Users\pandi\Documents\GitHub\logwatchdog\test_clean\logs\application.log
log_folder_path = C:\Users\pandi\Documents\GitHub\logwatchdog\test_clean\logs
log_file_extensions = *.log,*.txt,*.evtx
file_discovery_interval = 30
empty_monitor_delay = 10

[notifications]
email_enabled = false
smtp_server = smtp.gmail.com
smtp_port = 587
receiver_group = admin@company.com,ops@company.com
system_tray_notifications = true

[alerts]
exception_keywords = Exception,Error,Failure,Fail,Fatal,Issue,Crash,Close,Cannot,Wrong,unsupported,not found,retry,terminated,disconnected

